path: "/send"
method: "POST"
room: "!AAAAAAAAAAAAAAAAAA:example.com"
grace_period: 5
device_name: "My Device"
message_format: "plaintext"
message_type: "m.text"
auth_type:
auth_token:
force_json: false
ignore_empty_messages: false
