name: ci

on: [push, pull_request]

jobs:
  pycodestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install pycodestyle
      run: pip install pycodestyle
    - name: Check code style with PyCodestyle
      run: pycodestyle --count --max-line-length 120 webhook.py
